### ISSUE TITLE
'xyListFromGrob()' bug when grob has line decorations over enclosing polygon

### ISSUE THREAD

**Issue by trevorld** [pmur002/gridgeometry#2]
When I have a polygon with some decorative lines on it I'd expect `xyListFromGrob(gt, op = "union", closed=TRUE)` to return the boundary of the enclosing polygon but instead I get a `list()` with some WARNINGS.  Is this is a bug or do I misunderstand what `xyListFromGrob()` is supposed to do?:

```
gt <- grobTree(rectGrob(name = "main_shape"),
               grobTree(linesGrob(x=0.5), linesGrob(y=0.5), name = "gridlines")
               )
xyl <- gridGeometry::xyListFromGrob(gt, op = "union", closed=TRUE)
print(xyl)
```

```
Warning in min(x, na.rm = na.rm) :
  no non-missing arguments to min; returning Inf
Warning in max(x, na.rm = na.rm) :
  no non-missing arguments to max; returning -Inf
Warning in min(x, na.rm = na.rm) :
  no non-missing arguments to min; returning Inf
Warning in max(x, na.rm = na.rm) :
  no non-missing arguments to max; returning -Inf
list()
```

I'd instead expect something like the following

```
gt <- grobTree(rectGrob())
xyl <- gridGeometry::xyListFromGrob(gt, op = "union", closed=TRUE)
print(xyl)
```

```
grob GRID.rect.51  
  shape 1 
    x: 0 0 6.993817 ... [4 values]
    y: 0 6.989583 6.989583 ... [4 values]
```

**Comment by pmur002** [comment]
Yep.  Unfortunately, when collapsing the gTree with `polyclip::polyclip()` we end up reducing a list() result with another list() result (the two lines grobs), which produces the warnings and a final list() result.  I have modified the collapsing code so that we (in theory) never end up with a list() result (so something like your "union" retains the rect coordinates). 

A "workaround" to get the old behaviour (from previous version of 'gridGeometry' and R 4.1.*) is to use `op = "flatten"`.

Thanks for the report !
